### ISSUE TITLE
ColorSetting trait issue

### ISSUE THREAD

**Issue by shady2k** [i8beef/HomeAutio.Mqtt.GoogleHome#29] opened 2018-12-23 08:28 UTC
Trying to implement "action.devices.traits.ColorSetting" trait.
Device configuration looks like:

```
  "home/hall/strip": {
    "id": "home/hall/strip",
    "type": "action.devices.types.LIGHT",
    "willReportState": false,
    "roomHint": "Some Room",
    "name": {
      "defaultNames": [],
      "name": "strip",
      "nicknames": []
    },
    "deviceInfo": {
      "manufacturer": "Some Company",
      "model": "Some Model",
      "hwVersion": "1.0",
      "swVersion": "1.0"
    },
    "traits": [
      {
        "trait": "action.devices.traits.OnOff",
        "attributes": null,
        "commands": {
          "action.devices.commands.OnOff": {
            "on": "nodered/commandUpdates/led_hall_power/command"
          }
        },
        "state": {
          "on": {
            "topic": "openhab/stateUpdates/led_hall_power/state",
            "googleType": "bool",
            "valueMap": [
              {
                "mqtt": "ON",
                "type": "value",
                "google": true
              },
              {
                "mqtt": "OFF",
                "type": "value",
                "google": false
              }
            ]
          }
        }
      },
      {
        "trait": "action.devices.traits.Brightness",
        "attributes": null,
        "commands": {
          "action.devices.commands.BrightnessAbsolute": {
            "brightness": "nodered/commandUpdates/led_hall_white/command"
          }
        },
        "state": {
          "brightness": {
            "topic": "openhab/stateUpdates/led_hall_white/state",
            "googleType": "numeric",
            "valueMap": null
          }
        }
      },
      {
        "trait": "action.devices.traits.ColorSetting",
        "attributes": {
          "colorModel": "rgb",
          "commandOnlyColorSetting": true
        },
        "commands": {
          "action.devices.commands.ColorAbsolute": {
            "color.name": "nodered/commandUpdates/led_hall_color_name/command",
            "color.spectrumRGB": "nodered/commandUpdates/led_hall_color/command"
          }
        },
        "state": {
          "color.spectrumRgb": {
            "topic": "openhab/stateUpdates/led_hall_color/state",
            "googleType": "numeric",
            "valueMap": null
          }
        }
      }
    ],
    "customData": null
  }
}
```

In the log:
> 2018-12-23 11:20:59.495 +03:00 [Information] Received EXECUTE intent for commands: action.devices.commands.ColorAbsolute
> 2018-12-23 11:20:59.567 +03:00 [Information] Executed action method "HomeAutio.Mqtt.GoogleHome.Controllers.GoogleHomeController.Post (HomeAutio.Mqtt.GoogleHome)", returned result "Microsoft.AspNetCore.Mvc.OkObjectResult" in 96.3069ms.
> 2018-12-23 11:20:59.582 +03:00 [Information] Executing ObjectResult, writing value of type '"HomeAutio.Mqtt.GoogleHome.Models.Response.Response"'.

After that, program restarts. What I'm doing wrong?

**Comment by shady2k** [comment] 2018-12-23 12:44
Guessed by myself, it require "color.name" in the state section.

**Comment by shady2k** [comment] 2018-12-23 12:44
It is desirable here to add exception handling.

**Comment by i8beef** [comment] 2018-12-23 20:21
The problem is actually that there's no validation of configuration items to let you know about required stuff you might have missed. There is an assumption that every COMMAND parameter will have a matching STATE entry as well. This is because the command entry only gives a command a topic, but other configuration data (valueMaps) need to come from the state object. 

I can actually change that to just pass the original value through if a state object isn't present, but I'd have to think through what the implications are for QUERY intents then... as without the state entry you wouldn't be sending a value back to Google. Right now, I'm thinking this is a hard requirement though.

I will evaluate a validator though for the config entries.

**Comment by i8beef** [comment] 2018-12-24 04:08
So interesting thing... commandOnlyColorSetting seems to indicate a command only capability here. As such I'll add in a change that lets this go through without attempting to do ValueMapping to bypass the issue.

**Comment by shady2k** [comment] 2018-12-24 06:28
> I can actually change that to just pass the original value through if a state object isn't present

No need for this changes, it will be enough to write this in wiki. It is not obvious.
I will write after testing new release.

**Comment by i8beef** [comment] 2018-12-24 07:49
It isn't right as is. That commandOnlyColorSettings means a COMMAND ONLY setup where you didn't have the state parameters is VALID to Google here. Its a valid change to make.

**Comment by i8beef** [comment] 2018-12-26 05:00
Closing as this has been added at this point. Reopen if you feel there is more that needs to change here.

**Closed as completed by i8beef** 2018-12-26 05:00 UTC
