### ISSUE TITLE
Link in wiki page Config:-GoogleDevices.json wrong?

### ISSUE THREAD

**Issue by glsf91** [i8beef/HomeAutio.Mqtt.GoogleHome#96] opened 2020-10-30 16:58 UTC
I think the link in "Metadata generally follows the same structure that Google expects to be returned by a SYNC intent, with a few changes." is not the correct one. It does not link to Sync intent.

**Comment by i8beef** [comment] 2020-10-30 17:14
Closed as duplicate of #97

**Closed as completed by i8beef** 2020-10-30 17:14 UTC
